### ISSUE TITLE
Question regarding CIFAR 100 preparation

### ISSUE THREAD

**Issue by jd730** [gina9726/Deep-RTC#1]
Hi, I have a question regarding CIFAR 100 preparation.
Usually, we utilize CIFAR 100 as a python-version on their [webpage](https://www.cs.toronto.edu/~kriz/cifar.html), which is divided into `test` and `train` files.
However, according to the data preparation section on README.md, it should be saved as jpg with class hierarchy. According to train/valid/test splits in https://github.com/gina9726/Deep-RTC/tree/master/prepro/splits/cifar100, the file format is "Image{:5d}.jpg" and some indices are missing.

Could you tell me how to form CIFAR 100 dataset?

The Long-tailed version link just denotes the various long-tailed versions of tfrecord files.

Thank you.

**Comment by gina9726** [comment]
Sorry, I didn't notice this. I have updated the link to the image files in README.md, which are unpacked from the tf-record file provided by [https://github.com/richardaecn/class-balanced-loss](https://github.com/richardaecn/class-balanced-loss).
